version: '3.9'

services:
    nginx:
        image: nginx:1.19.9-alpine
        container_name: runroom-nginx
        volumes:
            - './app:/var/www/project'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - "8080:80"
        depends_on:
            - php
        networks: 
            - backend

    php:
        container_name: runroom-php
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
        volumes:
            - ./app:/var/www/project
        ports:
            - "9000:9000"
        networks:
            - backend

networks:
    backend: